apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: mysterium-ingress
  namespace: mysterium
spec:
  rules:
  - host: mysterium.tino.sh
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mysterium-service
            port: 
              number: 80
  tls:
  - hosts:
    - mysterium.tino.sh
    secretName: mysterium-tino-sh-tls
