apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mysterium
  name: mysterium-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
