apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysterium-app 
  name: mysterium-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4449
  selector:
    app: mysterium-app
